#!/usr/bin/env python3
"""
Build all 11 Core Rulebook classes for PF1e from concise data tables.

This is faster and far less error-prone than hand-writing 11 ~150-line JSON files.
For each class we encode the canonical CRB facts:
  - Hit die, skill ranks/level, key ability, alignment restriction
  - BAB progression (full / three_quarters / half)
  - Save progressions (good / poor) for Fort, Ref, Will
  - Class skill list (using our 35 standardized skill ids)
  - Weapon / armor proficiencies
  - Level-by-level features (level + name + short description)

Run from scripts/:
    python build_core_classes.py
"""
import json
from pathlib import Path

OUT_DIR = Path(__file__).parent.parent / "pf1e" / "resource_instances"

# Skill ids must match those declared in system/character_stats.rpgs
S = {
    "acrobatics": "acrobatics", "appraise": "appraise", "bluff": "bluff",
    "climb": "climb", "craft": "craft", "diplomacy": "diplomacy",
    "disable_device": "disable_device", "disguise": "disguise",
    "escape_artist": "escape_artist", "fly": "fly", "handle_animal": "handle_animal",
    "heal": "heal", "intimidate": "intimidate",
    "k_arcana": "knowledge_arcana", "k_dungeoneering": "knowledge_dungeoneering",
    "k_engineering": "knowledge_engineering", "k_geography": "knowledge_geography",
    "k_history": "knowledge_history", "k_local": "knowledge_local",
    "k_nature": "knowledge_nature", "k_nobility": "knowledge_nobility",
    "k_planes": "knowledge_planes", "k_religion": "knowledge_religion",
    "linguistics": "linguistics", "perception": "perception", "perform": "perform",
    "profession": "profession", "ride": "ride", "sense_motive": "sense_motive",
    "sleight_of_hand": "sleight_of_hand", "spellcraft": "spellcraft",
    "stealth": "stealth", "survival": "survival", "swim": "swim",
    "use_magic_device": "use_magic_device",
}

# Compact class definitions. (Fighter is already built; included here for re-emit consistency.)
CLASSES = [
    {
        "id": "barbarian",
        "name": "Barbarian",
        "alignment_restriction": "any non-lawful",
        "hit_die": "d12", "hp_per_level": 12,
        "skill_ranks_per_level": 4, "skill_ranks_ability": "intelligence",
        "starting_wealth": "3d6 × 10 gp",
        "bab": "full",
        "fort": "good", "ref": "poor", "will": "poor",
        "class_skills": [S["acrobatics"], S["climb"], S["craft"], S["handle_animal"],
                         S["intimidate"], S["k_nature"], S["perception"], S["ride"],
                         S["survival"], S["swim"]],
        "weapons": ["simple", "martial"],
        "armor": ["light", "medium"], "shields": ["buckler", "light", "heavy"],
        "features": [
            (1, "Fast Movement", "+10 ft to land speed in light/medium armor."),
            (1, "Rage", "Enter a rage for rounds/day = 4 + Con mod (+2/level). +4 Str/Con, +2 Will, -2 AC."),
            (2, "Rage Power", "Gain a rage power; another every even level."),
            (2, "Uncanny Dodge", "Retain Dex bonus when flat-footed."),
            (3, "Trap Sense +1", "+1 vs traps."),
            (5, "Improved Uncanny Dodge", "Cannot be flanked except by rogue 4 levels higher."),
            (6, "Trap Sense +2", ""),
            (7, "Damage Reduction 1/—", ""),
            (9, "Trap Sense +3", ""),
            (10, "Damage Reduction 2/—", ""),
            (11, "Greater Rage", "+6 Str/Con, +3 Will while raging."),
            (12, "Trap Sense +4", ""),
            (13, "Damage Reduction 3/—", ""),
            (14, "Indomitable Will", "+4 vs enchantment while raging."),
            (15, "Trap Sense +5", ""),
            (16, "Damage Reduction 4/—", ""),
            (17, "Tireless Rage", "No longer fatigued after raging."),
            (18, "Trap Sense +6", ""),
            (19, "Damage Reduction 5/—", ""),
            (20, "Mighty Rage", "+8 Str/Con, +4 Will while raging."),
        ],
    },
    {
        "id": "bard",
        "name": "Bard",
        "alignment_restriction": "any non-lawful",
        "hit_die": "d8", "hp_per_level": 8,
        "skill_ranks_per_level": 6, "skill_ranks_ability": "intelligence",
        "starting_wealth": "3d6 × 10 gp",
        "bab": "three_quarters",
        "fort": "poor", "ref": "good", "will": "good",
        "class_skills": [S["acrobatics"], S["appraise"], S["bluff"], S["climb"], S["craft"],
                         S["diplomacy"], S["disguise"], S["escape_artist"], S["intimidate"],
                         S["k_arcana"], S["k_dungeoneering"], S["k_engineering"], S["k_geography"],
                         S["k_history"], S["k_local"], S["k_nature"], S["k_nobility"],
                         S["k_planes"], S["k_religion"], S["linguistics"], S["perception"],
                         S["perform"], S["profession"], S["sense_motive"], S["sleight_of_hand"],
                         S["spellcraft"], S["stealth"], S["use_magic_device"]],
        "weapons": ["simple", "longsword", "rapier", "sap", "short sword", "shortbow", "whip"],
        "armor": ["light"], "shields": ["buckler", "light", "heavy"],
        "spellcasting": {"type": "spontaneous", "tradition": "arcane", "ability": "charisma", "max_spell_level": 6},
        "features": [
            (1, "Bardic Knowledge", "Add half level (min 1) to all Knowledge checks; may make untrained."),
            (1, "Bardic Performance", "Rounds/day = 4 + Cha mod (+2/level)."),
            (1, "Cantrips", "Knows 0-level spells castable at will."),
            (1, "Countersong", ""),
            (1, "Distraction", ""),
            (1, "Fascinate", ""),
            (1, "Inspire Courage +1", "+1 morale to attack/damage and vs fear/charm for allies."),
            (2, "Versatile Performance", "Substitute Perform for two other skills."),
            (2, "Well-Versed", "+4 vs bardic/sonic effects."),
            (3, "Inspire Competence +2", ""),
            (5, "Lore Master", "Take 10 on any Knowledge check."),
            (5, "Inspire Courage +2", ""),
            (6, "Suggestion", ""),
            (8, "Dirge of Doom", ""),
            (9, "Inspire Greatness", ""),
            (11, "Inspire Courage +3", ""),
            (12, "Soothing Performance", ""),
            (14, "Frightening Tune", ""),
            (15, "Inspire Heroics", ""),
            (17, "Inspire Courage +4", ""),
            (18, "Mass Suggestion", ""),
            (20, "Deadly Performance", ""),
        ],
    },
    {
        "id": "cleric",
        "name": "Cleric",
        "alignment_restriction": "within one step of deity",
        "hit_die": "d8", "hp_per_level": 8,
        "skill_ranks_per_level": 2, "skill_ranks_ability": "intelligence",
        "starting_wealth": "4d6 × 10 gp",
        "bab": "three_quarters",
        "fort": "good", "ref": "poor", "will": "good",
        "class_skills": [S["appraise"], S["craft"], S["diplomacy"], S["heal"],
                         S["k_arcana"], S["k_history"], S["k_nobility"], S["k_planes"],
                         S["k_religion"], S["linguistics"], S["profession"], S["sense_motive"], S["spellcraft"]],
        "weapons": ["simple", "deity's favored weapon"],
        "armor": ["light", "medium", "heavy"], "shields": ["buckler", "light", "heavy"],
        "spellcasting": {"type": "prepared", "tradition": "divine", "ability": "wisdom", "max_spell_level": 9},
        "features": [
            (1, "Aura", "Strong aura matching alignment."),
            (1, "Channel Energy", "1d6 positive/negative energy (Cleric level rounded up by every 2)."),
            (1, "Domains", "Choose 2 domains; gain domain powers and bonus domain spells."),
            (1, "Orisons", "Cast 0-level spells at will."),
            (1, "Spontaneous Casting", "Convert prepared spells to cure/inflict spells of same level."),
            (8, "Channel Energy 4d6", ""),
            (20, "Channel Energy 10d6", "Max channel energy progression."),
        ],
    },
    {
        "id": "druid",
        "name": "Druid",
        "alignment_restriction": "neutral (any neutral)",
        "hit_die": "d8", "hp_per_level": 8,
        "skill_ranks_per_level": 4, "skill_ranks_ability": "intelligence",
        "starting_wealth": "2d6 × 10 gp",
        "bab": "three_quarters",
        "fort": "good", "ref": "poor", "will": "good",
        "class_skills": [S["climb"], S["craft"], S["fly"], S["handle_animal"], S["heal"],
                         S["k_geography"], S["k_nature"], S["perception"], S["profession"],
                         S["ride"], S["spellcraft"], S["survival"], S["swim"]],
        "weapons": ["club", "dagger", "dart", "quarterstaff", "scimitar", "scythe",
                    "sickle", "shortspear", "sling", "spear"],
        "armor": ["light", "medium (non-metal)"], "shields": ["wooden"],
        "spellcasting": {"type": "prepared", "tradition": "divine", "ability": "wisdom", "max_spell_level": 9},
        "features": [
            (1, "Nature Bond", "Animal companion or domain."),
            (1, "Nature Sense", "+2 K. Nature & Survival."),
            (1, "Orisons", ""),
            (1, "Wild Empathy", "Improve attitude of animal."),
            (2, "Woodland Stride", "Move through undergrowth at full speed."),
            (3, "Trackless Step", "Leave no trail unless desired."),
            (4, "Resist Nature's Lure", "+4 save vs fey spell-likes."),
            (4, "Wild Shape 1/day", ""),
            (6, "Wild Shape 2/day", ""),
            (8, "Wild Shape 3/day", ""),
            (9, "Venom Immunity", ""),
            (13, "A Thousand Faces", ""),
            (15, "Timeless Body", ""),
            (20, "Wild Shape 8/day (incl. elementals huge)", ""),
        ],
    },
    # Fighter already exists as fighter__crb_; re-emit for parity
    {
        "id": "fighter", "name": "Fighter",
        "alignment_restriction": "any",
        "hit_die": "d10", "hp_per_level": 10,
        "skill_ranks_per_level": 2, "skill_ranks_ability": "intelligence",
        "starting_wealth": "5d6 × 10 gp",
        "bab": "full", "fort": "good", "ref": "poor", "will": "poor",
        "class_skills": [S["climb"], S["craft"], S["handle_animal"], S["intimidate"],
                         S["k_dungeoneering"], S["k_engineering"], S["profession"],
                         S["ride"], S["survival"], S["swim"]],
        "weapons": ["simple", "martial"],
        "armor": ["light", "medium", "heavy"], "shields": ["buckler", "light", "heavy", "tower"],
        "features": [
            (1, "Bonus Combat Feat", "Choose a combat feat."),
            (2, "Bonus Combat Feat", ""),
            (2, "Bravery +1", "+1 vs fear."),
            (3, "Armor Training 1", ""),
            (4, "Bonus Combat Feat", ""),
            (5, "Weapon Training 1", "+1 atk/dmg with chosen group."),
            (6, "Bonus Combat Feat", ""),
            (6, "Bravery +2", ""),
            (7, "Armor Training 2", ""),
            (8, "Bonus Combat Feat", ""),
            (9, "Weapon Training 2", ""),
            (10, "Bonus Combat Feat", ""),
            (10, "Bravery +3", ""),
            (11, "Armor Training 3", ""),
            (12, "Bonus Combat Feat", ""),
            (13, "Weapon Training 3", ""),
            (14, "Bonus Combat Feat", ""),
            (14, "Bravery +4", ""),
            (15, "Armor Training 4", ""),
            (16, "Bonus Combat Feat", ""),
            (17, "Weapon Training 4", ""),
            (18, "Bonus Combat Feat", ""),
            (18, "Bravery +5", ""),
            (19, "Armor Mastery", "DR 5/—."),
            (20, "Bonus Combat Feat", ""),
            (20, "Weapon Mastery", "Auto-confirm crits, +1 crit mult."),
        ],
    },
    {
        "id": "monk", "name": "Monk",
        "alignment_restriction": "any lawful",
        "hit_die": "d8", "hp_per_level": 8,
        "skill_ranks_per_level": 4, "skill_ranks_ability": "intelligence",
        "starting_wealth": "1d6 × 10 gp",
        "bab": "three_quarters",
        "fort": "good", "ref": "good", "will": "good",
        "class_skills": [S["acrobatics"], S["climb"], S["craft"], S["escape_artist"],
                         S["intimidate"], S["k_history"], S["k_religion"], S["perception"],
                         S["perform"], S["profession"], S["ride"], S["sense_motive"],
                         S["stealth"], S["swim"]],
        "weapons": ["club", "crossbow (light/heavy)", "dagger", "handaxe", "javelin",
                    "kama", "nunchaku", "quarterstaff", "sai", "shortspear", "shuriken",
                    "siangham", "sling", "spear", "temple sword"],
        "armor": [], "shields": [],
        "features": [
            (1, "AC Bonus", "+Wis mod & +1/4 levels to AC when unarmored & unencumbered."),
            (1, "Bonus Feat", "Choose from list (Combat Reflexes, Dodge, Improved Grapple, etc.)."),
            (1, "Flurry of Blows", "Extra attack at full BAB; unarmed or monk weapon."),
            (1, "Stunning Fist", ""),
            (1, "Unarmed Strike", "1d6 (medium); deals lethal."),
            (2, "Bonus Feat", ""),
            (2, "Evasion", "Half damage on failed Reflex save = no damage."),
            (3, "Fast Movement +10 ft", ""),
            (3, "Maneuver Training", "BAB = monk level for CMB."),
            (3, "Still Mind", "+2 vs enchantments."),
            (4, "Ki Pool", "Wis mod + 1/2 level points/day."),
            (4, "Slow Fall 20 ft", ""),
            (5, "High Jump", ""),
            (5, "Purity of Body", "Immune to disease."),
            (7, "Wholeness of Body", ""),
            (9, "Improved Evasion", ""),
            (11, "Diamond Body", "Immune to poison."),
            (12, "Abundant Step", ""),
            (13, "Diamond Soul", "SR 10 + monk level."),
            (15, "Quivering Palm", ""),
            (17, "Timeless Body", ""),
            (17, "Tongue of the Sun and Moon", ""),
            (19, "Empty Body", ""),
            (20, "Perfect Self", "Outsider type; DR 10/chaotic."),
        ],
    },
    {
        "id": "paladin", "name": "Paladin",
        "alignment_restriction": "lawful good",
        "hit_die": "d10", "hp_per_level": 10,
        "skill_ranks_per_level": 2, "skill_ranks_ability": "intelligence",
        "starting_wealth": "5d6 × 10 gp",
        "bab": "full",
        "fort": "good", "ref": "poor", "will": "good",
        "class_skills": [S["craft"], S["diplomacy"], S["handle_animal"], S["heal"],
                         S["k_nobility"], S["k_religion"], S["profession"], S["ride"], S["sense_motive"], S["spellcraft"]],
        "weapons": ["simple", "martial"],
        "armor": ["light", "medium", "heavy"], "shields": ["buckler", "light", "heavy", "tower"],
        "spellcasting": {"type": "prepared", "tradition": "divine", "ability": "charisma",
                         "max_spell_level": 4, "begins_at_level": 4},
        "features": [
            (1, "Aura of Good", ""),
            (1, "Detect Evil", "At will."),
            (1, "Smite Evil 1/day", "Add Cha mod to atk, level to damage vs evil."),
            (2, "Divine Grace", "Add Cha mod to all saves."),
            (2, "Lay on Hands", "Heal (level/2) × Cha-mod times per day, 1d6 per 2 levels."),
            (3, "Aura of Courage", "+4 vs fear for self & allies in 10 ft."),
            (3, "Divine Health", "Immune to disease."),
            (3, "Mercy", "Lay on Hands also removes a condition."),
            (4, "Channel Positive Energy", ""),
            (5, "Divine Bond", "Weapon or mount."),
            (5, "Smite Evil 2/day", ""),
            (8, "Aura of Resolve", ""),
            (8, "Smite Evil 3/day", ""),
            (11, "Aura of Justice", ""),
            (11, "Smite Evil 4/day", ""),
            (14, "Aura of Faith", ""),
            (14, "Smite Evil 5/day", ""),
            (17, "Aura of Righteousness", ""),
            (17, "Smite Evil 6/day", ""),
            (20, "Holy Champion", "Smite banishes evil outsiders."),
        ],
    },
    {
        "id": "ranger", "name": "Ranger",
        "alignment_restriction": "any",
        "hit_die": "d10", "hp_per_level": 10,
        "skill_ranks_per_level": 6, "skill_ranks_ability": "intelligence",
        "starting_wealth": "5d6 × 10 gp",
        "bab": "full",
        "fort": "good", "ref": "good", "will": "poor",
        "class_skills": [S["climb"], S["craft"], S["handle_animal"], S["heal"], S["intimidate"],
                         S["k_dungeoneering"], S["k_geography"], S["k_nature"], S["perception"],
                         S["profession"], S["ride"], S["spellcraft"], S["stealth"], S["survival"], S["swim"]],
        "weapons": ["simple", "martial"],
        "armor": ["light", "medium"], "shields": ["buckler", "light", "heavy"],
        "spellcasting": {"type": "prepared", "tradition": "divine", "ability": "wisdom",
                         "max_spell_level": 4, "begins_at_level": 4},
        "features": [
            (1, "1st Favored Enemy", "+2 atk/dmg/skill vs chosen creature type."),
            (1, "Track", "Add half ranger level to Survival to track."),
            (1, "Wild Empathy", ""),
            (2, "Combat Style Feat", "Bonus feat from chosen archery or two-weapon list."),
            (3, "Endurance", "Bonus feat."),
            (3, "Favored Terrain", "+2 init/Knowledge geo/Per/Stealth/Survival in terrain."),
            (4, "Hunter's Bond", "Animal companion or +half level to allies' atk vs FE."),
            (5, "2nd Favored Enemy", ""),
            (6, "Combat Style Feat", ""),
            (7, "Woodland Stride", ""),
            (8, "Swift Tracker", "Track at normal speed."),
            (9, "Evasion", ""),
            (10, "3rd Favored Enemy", ""),
            (10, "Combat Style Feat", ""),
            (11, "Quarry", ""),
            (12, "Camouflage", ""),
            (14, "Combat Style Feat", ""),
            (15, "4th Favored Enemy", ""),
            (16, "Improved Evasion", ""),
            (17, "Hide in Plain Sight", ""),
            (18, "Combat Style Feat", ""),
            (19, "Improved Quarry", ""),
            (20, "5th Favored Enemy", ""),
            (20, "Master Hunter", "Standard action kill of favored enemy."),
        ],
    },
    {
        "id": "rogue", "name": "Rogue",
        "alignment_restriction": "any",
        "hit_die": "d8", "hp_per_level": 8,
        "skill_ranks_per_level": 8, "skill_ranks_ability": "intelligence",
        "starting_wealth": "4d6 × 10 gp",
        "bab": "three_quarters",
        "fort": "poor", "ref": "good", "will": "poor",
        "class_skills": [S["acrobatics"], S["appraise"], S["bluff"], S["climb"], S["craft"],
                         S["diplomacy"], S["disable_device"], S["disguise"], S["escape_artist"],
                         S["intimidate"], S["k_dungeoneering"], S["k_local"], S["linguistics"],
                         S["perception"], S["perform"], S["profession"], S["sense_motive"],
                         S["sleight_of_hand"], S["stealth"], S["swim"], S["use_magic_device"]],
        "weapons": ["simple", "hand crossbow", "rapier", "sap", "shortbow", "short sword"],
        "armor": ["light"], "shields": [],
        "features": [
            (1, "Sneak Attack +1d6", "+1d6 dmg vs flat-footed/flanked, +1d6 every 2 levels."),
            (1, "Trapfinding", "+1/2 level to Perception/Disable Device for traps."),
            (2, "Evasion", ""),
            (2, "Rogue Talent", "Every even level."),
            (3, "Trap Sense +1", ""),
            (4, "Uncanny Dodge", ""),
            (8, "Improved Uncanny Dodge", ""),
            (10, "Advanced Talents", "Every even level after 10."),
            (20, "Master Strike", "Standard-action sneak attack inflicts sleep/paralysis/death."),
        ],
    },
    {
        "id": "sorcerer", "name": "Sorcerer",
        "alignment_restriction": "any",
        "hit_die": "d6", "hp_per_level": 6,
        "skill_ranks_per_level": 2, "skill_ranks_ability": "intelligence",
        "starting_wealth": "2d6 × 10 gp",
        "bab": "half",
        "fort": "poor", "ref": "poor", "will": "good",
        "class_skills": [S["appraise"], S["bluff"], S["craft"], S["fly"],
                         S["intimidate"], S["k_arcana"], S["profession"], S["spellcraft"], S["use_magic_device"]],
        "weapons": ["simple"],
        "armor": [], "shields": [],
        "spellcasting": {"type": "spontaneous", "tradition": "arcane", "ability": "charisma", "max_spell_level": 9},
        "features": [
            (1, "Bloodline", "Choose a bloodline; gain bonus spells, class skills, feats, powers."),
            (1, "Bloodline Power", "1st bloodline power."),
            (1, "Cantrips", "0-level spells castable at will."),
            (1, "Eschew Materials", "Cast without inexpensive material components."),
            (3, "Bloodline Power", ""),
            (3, "Bloodline Spell (1st)", ""),
            (7, "Bloodline Spell (3rd)", ""),
            (9, "Bloodline Power", ""),
            (11, "Bloodline Spell (5th)", ""),
            (15, "Bloodline Power & Spell (7th)", ""),
            (19, "Bloodline Spell (9th)", ""),
            (20, "Bloodline Power (capstone)", ""),
        ],
    },
    {
        "id": "wizard", "name": "Wizard",
        "alignment_restriction": "any",
        "hit_die": "d6", "hp_per_level": 6,
        "skill_ranks_per_level": 2, "skill_ranks_ability": "intelligence",
        "starting_wealth": "2d6 × 10 gp",
        "bab": "half",
        "fort": "poor", "ref": "poor", "will": "good",
        "class_skills": [S["appraise"], S["craft"], S["fly"], S["k_arcana"],
                         S["k_dungeoneering"], S["k_engineering"], S["k_geography"],
                         S["k_history"], S["k_local"], S["k_nature"], S["k_nobility"],
                         S["k_planes"], S["k_religion"], S["linguistics"], S["profession"], S["spellcraft"]],
        "weapons": ["club", "dagger", "heavy crossbow", "light crossbow", "quarterstaff"],
        "armor": [], "shields": [],
        "spellcasting": {"type": "prepared", "tradition": "arcane", "ability": "intelligence", "max_spell_level": 9},
        "features": [
            (1, "Arcane Bond", "Bonded item or familiar."),
            (1, "Arcane School", "Choose specialist school or universalist."),
            (1, "Cantrips", "0-level spells at will once prepared."),
            (1, "Scribe Scroll", "Bonus item creation feat."),
            (5, "Bonus Feat", "Item creation or metamagic."),
            (10, "Bonus Feat", ""),
            (15, "Bonus Feat", ""),
            (20, "Bonus Feat", ""),
        ],
    },
]


def build_class_json(c: dict) -> dict:
    return {
        "resource_id": "class",
        "stats": {
            "id": f"{c['id']}__crb_",
            "name": {"value": c["name"]},
            "source": {"value": "crb"},
            "description": {"value":
                f"### Hit Die\n{c['hit_die']}.\n\n"
                f"### Starting Wealth\n{c['starting_wealth']}\n\n"
                f"### Skill Ranks per Level\n{c['skill_ranks_per_level']} + Int modifier.\n\n"
                f"### Alignment\n{c['alignment_restriction']}.\n\n"
                f"### Class Features\nSee the level table below."
            },
            "hit_die": {"value": c["hit_die"]},
            "class_hp_per_level": {"value": c["hp_per_level"]},
            "skill_ranks_per_level": {"value": c["skill_ranks_per_level"]},
            "skill_ranks_ability": {"value": c["skill_ranks_ability"]},
            "bab_progression": {"value": c["bab"]},
            "fortitude_progression": {"value": c["fort"]},
            "reflex_progression": {"value": c["ref"]},
            "will_progression": {"value": c["will"]},
            "class_skills": {"value": c["class_skills"]},
            "starting_wealth": {"value": c["starting_wealth"]},
            "alignment_restriction": {"value": c["alignment_restriction"]},
            "weapon_proficiencies": {"value": c["weapons"]},
            "armor_proficiencies": {"value": c["armor"]},
            "shield_proficiencies": {"value": c["shields"]},
            **({"spellcasting": {"value": c["spellcasting"]}} if c.get("spellcasting") else {}),
            "class_features": {"value": [
                {"level": lvl, "name": name, "description": desc}
                for (lvl, name, desc) in c["features"]
            ]},
        },
    }


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for c in CLASSES:
        data = build_class_json(c)
        path = OUT_DIR / f"class_{c['id']}__crb_.rpg.json"
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        written += 1
        print(f"wrote {path.name}")
    print(f"\nDone: {written} classes")


if __name__ == "__main__":
    main()
